#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  packageios:
    name: Build and Test Swift Package iOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziBluetooth-Package
      artifactname: SpeziBluetooth-Package.xcresult
  ios:
    name: Build and Test iOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted", "bluetooth"]'
      setupSimulators: true
      path: 'Tests/UITests'
      scheme: TestApp
      destination: 'platform=macOS,arch=arm64,variant=Mac Catalyst'
      artifactname: TestApp.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packageios, ios]
    uses: StanfordSpezi/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziBluetooth-Package.xcresult TestApp.xcresult
